-- MySQL Script generated by MySQL Workbench
-- 10/09/21 17:45:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ventas` ;

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET latin1 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Productos` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(255) NOT NULL,
  `vlrUnitario` INT NOT NULL,
  `estado` INT NULL COMMENT '1 terminado\n0 pendiente',
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `vlrUnitario_UNIQUE` (`vlrUnitario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `docCliente` INT UNSIGNED NOT NULL COMMENT '	',
  `primerNombre` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `dirección` TEXT NOT NULL,
  `telefono1` FLOAT NOT NULL,
  `telefono2` FLOAT NULL,
  `eMail` TEXT NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Vendedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Vendedores` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Vendedores` (
  `idVendedores` INT NOT NULL AUTO_INCREMENT,
  `nombreVendedor` TEXT NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `eMail` TEXT NOT NULL,
  PRIMARY KEY (`idVendedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `correoUsuario` TEXT NOT NULL,
  `tipoUsuario` INT NULL COMMENT '0 usuario vendedor\n1 usuaro administrador',
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ventas`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT 'numero del pedido',
  `idClientes` INT NOT NULL COMMENT 'identificacion del cliente',
  `idVendedores` INT NOT NULL COMMENT 'identificacion del vendedor',
  `fPedido` DATE NOT NULL COMMENT 'Fecha del pedido',
  `estado` VARCHAR(1) NOT NULL COMMENT 'Estado del pedido\nen proceso (p)\ncancelada  (c)\nentregada (e)',
  `valor` INT NOT NULL COMMENT 'Valor del producto	',
  `vendedor` INT NOT NULL COMMENT 'usuario registrado',
  `Usuario` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idClientes_idx` (`idClientes` ASC),
  INDEX `idVendores_idx` (`idVendedores` ASC),
  INDEX `idUsuario_idx` (`Usuario` ASC),
  CONSTRAINT `idClientes`
    FOREIGN KEY (`idClientes`)
    REFERENCES `ventas`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVendores`
    FOREIGN KEY (`idVendedores`)
    REFERENCES `ventas`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `ventas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`.`itemsPedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`itemsPedidos` ;

CREATE TABLE IF NOT EXISTS `ventas`.`itemsPedidos` (
  `iditemsPedidos` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idProductos` INT NOT NULL COMMENT 'identificacion del pruducto solicitado',
  `cantidad` INT UNSIGNED NOT NULL COMMENT 'cantidad solicitada',
  `vlrUnitario` INT NOT NULL COMMENT 'valor unitario del producto',
  `VlrTotal` INT NOT NULL COMMENT 'Valor Total del producto\ncantidad X vlrUnitario',
  `usuario` INT NOT NULL,
  PRIMARY KEY (`iditemsPedidos`),
  INDEX `Pedido_idx` (`idPedido` ASC),
  INDEX `Producto_idx` (`idProductos` ASC),
  INDEX `Usuario_idx` (`usuario` ASC),
  CONSTRAINT `Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `ventas`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Producto`
    FOREIGN KEY (`idProductos`)
    REFERENCES `ventas`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `ventas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;






